Issue119 식당 추가 요청 게시판 구현
The-Fellowship-of-the-matzip/mat.zip-front pull request #120
Opened 2022-09-04 07:27 UTC by uk960214

기존 디자인과 기획에서 일부 변경되었습니다.

# 1. 게시판 항목 변경
기존에는 작성자 + 이름 + 등록 여부에 그 줄을 클릭하면 상세 정보로 모든 정보를 보게 되어 있었는데 자리가 좁음 + 클릭해야 한다는 것이 명확하지 않아서 이름 + 등록 여부 + 상세보기 버튼으로 구현하고 나머지 상세정보는 모두 모달에 넣었습니다.

# 2. 입력 바텀시트에 카테고리, 이름 순서로 나옵니다.

최대한 간단히 빠르게 구현하려고 한 거여서 구멍이 여기저기 많을텐데 우선은 일단 작동 되도록 구현해놓았습니다.

closed #119

2022-09-07 04:15 UTC, liswktjs reviewed
성실한 블링 👍

2022-09-07 04:15 UTC, liswktjs commented on src/components/pages/StoreRequestPage/StoreRequestBottomSheet/StoreRequestCreateBottomSheet.tsx
> +    }
name에 대한 유효성 검사를 안 해도 괜찮나요? 글자수 제한 같이 뭐 한글자 이상 20글자 이하 등등

2022-09-07 04:15 UTC, liswktjs commented on src/components/pages/StoreRequestPage/StoreRequestBottomSheet/StoreRequestEditBottomSheet.tsx
> +    }
이부분도 이름에 대한 유효성 검사가 필요하지 않을까요? 서버에서 제시한 이름 제한 글자는 없나요..?🤔

2022-09-07 04:15 UTC, liswktjs commented on src/components/pages/StoreRequestPage/StoreRequestDetailModal/StoreRequestDetailModal.tsx
> +} as const;
👍

2022-09-07 04:15 UTC, liswktjs commented on src/constants/categories.tsx
> +} as const;
앞에서 파일 내에 선언되어 있던 상수인것 같은데 앞 부분의 상수를 지우는 등의 추가작업이 필요할 거 같네요!

2022-09-07 04:22 UTC, nan-noo commented on src/api/fetchStoreRequests.tsx
> +// }
😤

2022-09-07 07:04 UTC, uk960214 commented on src/api/fetchStoreRequests.tsx
> +// }
이거는 쿼리 키 타입을 이렇게 사용하고 싶은데 적용하기에 시간이 부족하고 건드려야 할 부분이 많은거 같아서 일단 주석으로 남겨뒀습니다!

2022-09-07 10:17 UTC, nan-noo requested changes

2022-09-07 10:17 UTC, nan-noo commented on src/api/fetchStoreRequests.tsx
> +  const [, { size, campusId }] = queryKey;
왜 이렇게 가져오나요? size, campusId

2022-09-11 12:51 UTC, uk960214 commented on src/components/common/BottomSheet/BottomSheet.tsx
> +  }, []);
바텀 시트가 마운트 될 때 1. 뒷 배경이 스크롤 되는 것을 방지하고 2. 스크롤이 아래로 내려간 상태면 그 위치에 생성되도록 해주고/정리해주는 이펙트 훅입니다!

2022-09-11 12:52 UTC, uk960214 commented on src/api/fetchStoreRequests.tsx
> +  const [, { size, campusId }] = queryKey;
queryKey를 통해서 매개 변수를 전달할 수 있기 때문이죠! useQuery 하는 곳에서 저 두 가지를 queryKey로 추가해주면 fetch 함수에서도 쓸 수 있습니다!

2022-09-11 13:48 UTC, uk960214 commented on src/api/fetchStoreRequests.tsx
> +// }
근데 다들 불편해 하시니까 나중에 더 쓸모있을 때까지 지워놓겠습니다..

2022-09-11 13:49 UTC, uk960214 commented on src/api/sendStoreReqeustDeleteRequest.tsx
> +    const accessToken = window.sessionStorage.getItem("accessToken") as string;
했습니다!

2022-09-11 13:49 UTC, uk960214 commented on src/api/sendStoreRequestPostRequest.tsx
> +    const accessToken = window.sessionStorage.getItem("accessToken") as string;
얘도 했습니다!

2022-09-11 13:49 UTC, uk960214 commented on src/api/sendStoreRequestPutRequest.tsx
> +    const accessToken = window.sessionStorage.getItem("accessToken") as string;
얘도!

2022-09-11 13:50 UTC, uk960214 commented on src/components/pages/StoreRequestPage/StoreRequestBottomSheet/StoreRequestCreateBottomSheet.tsx
> +    const categoryId = formData.get("categoryId") as string;
코드가 엄청 길어지고 타스를 모르면 조금 이해하기 어려워졌지만 그래도 다 타입 가드 사용하도록 변경했습니다.

2022-09-11 13:50 UTC, uk960214 commented on src/components/pages/StoreRequestPage/StoreRequestBottomSheet/StoreRequestCreateBottomSheet.tsx
> +    }
얘기는 없었는데 50글자까지를 임의로 제한으로 걸었습니다. 최소는 0만 아니도록 했으니 괜찮을 것 같아요

2022-09-11 13:50 UTC, uk960214 commented on src/components/pages/StoreRequestPage/StoreRequestBottomSheet/StoreRequestEditBottomSheet.tsx
> +    }
위와 마찬가지로 적용했습니다.

2022-09-11 13:50 UTC, uk960214 commented on src/constants/categories.tsx
> +} as const;
지우고 통합했습니다!

2022-09-11 13:51 UTC, uk960214 commented on src/mock/data.ts
>  // TODO: 백엔드와 카테고리 종류 및 id 정하기
지웠고 여기 파일에 있는 category 상수도 필요하지 않은 것 같아서 지우고, 때문에 오류나는 것 전부 고쳤습니다.

2022-09-11 14:00 UTC, uk960214 commented on src/types/global.d.ts
> +declare const categories = {
원래는 하단에 타입에서 카테고리의 키 타입을 가지고 오도록 하고 싶었는데 여러가지 난관에 부딪혀 그냥 없애버리고 리터럴 타입으로 추가했습니다. (대표적으로는 d.ts 파일에는 import 해올 수 없는 것). 그래서 생각의 전환으로 먼저 CategoryId라는 타입을 전역 타입으로 선언하고 StoreRequest 타입을 비롯한 다른 타입에서 참조할 수 있게 변경했습니다.

2022-09-12 12:15 UTC, nan-noo approved these changes

2022-09-12 12:15 UTC, nan-noo commented on src/api/fetchStoreRequests.tsx
> +  const [, { size, campusId }] = queryKey;
fetch함수 외부에서 쿼리키를 설정할 때 `['string~~', {size, campusId}]` 로 계속 맞춰줘야 하는 번거로움이 있지 않을까요??
`{size, campusId}`만 가져와도 좋을 것 같아용

2022-09-12 12:15 UTC, nan-noo commented on src/components/pages/CategoryDetailPage/CategoryDetailPage.tsx
> +// import { categories } from "mock/data";
주석!!

2022-09-12 12:27 UTC, liswktjs approved these changes
굿👍 태태가 먼저 리뷰를 남겨서 더 할말이 없네용

2022-09-12 14:58 UTC, uk960214 commented on src/api/fetchStoreRequests.tsx
> +  const [, { size, campusId }] = queryKey;
음.. 어차피 해당 요청을 캐싱하려면 쿼리키에서 두 가지가 제외되는 경우는 없을 것 같고.. 외부에서 따로 size와 campusId만 받아오려면 고차 함수처럼 `(size, campusId) => async ({ pageParam = 0, queryKey }: Params) => {}` 형식으로 될 텐데 이렇게 변경하는 것이 개인적으로는 더 어색하다고 생각합니다! 어떻게 생각하시나요? cc.@liswktjs

2022-09-12 14:58 UTC, uk960214 commented on src/components/pages/CategoryDetailPage/CategoryDetailPage.tsx
> +// import { categories } from "mock/data";
제거했습니다!

2022-09-12 15:01 UTC, merged