Issue121 리뷰 수정 삭제 구현
The-Fellowship-of-the-matzip/mat.zip-front pull request #123
Opened 2022-09-11 12:50 UTC by liswktjs

Close #121 

- 작성자인 경우, 게시글을 수정, 삭제할 수 있는 button을 DropDownBox와 MeatballButton을 활용하여 구현 
- 수정 , 삭제에 대한 비동기 통신 로직 구현 
- 리뷰 수정하는 내용을 적기 위한 ReviewBottomSheet컴포넌트 구현 
- api 변경에 따른, 기존의 컴포넌트 수정

2022-09-14 10:14 UTC, uk960214 requested changes

2022-09-14 10:14 UTC, uk960214 commented on public/index.html
> +    <div id="bottom-sheet"></div>
root에 렌더링 하지 않고 따로 바텀시트 `div`를 만들어준 이유가 있나요?

2022-09-14 10:14 UTC, uk960214 commented on src/components/common/MeatballButton/MeatballButton.tsx
> +);
svg 컴포넌트를 이렇게 함께 가지고 있으면 추후에 아이콘 이미지를 바꾸고 싶을 때 불편함이 생기지는 않을까요?

2022-09-14 10:14 UTC, uk960214 commented on src/components/common/DropDownBox/DropDownBox.style.tsx
> +    ${right && `right: ${right};`}
position을 absolute로 고정하고 상위 컴포넌트에서 직접 위치를 px까지 넘겨주는 것이 최선일까요? dropdown이라는 구성 요소의 특징이 호출한 부모요소의 바로 하단에 생기는 요소라는 점인데 이 점을 고려하면 이렇게 모든 위치를 지정하는 것보다 더 나은 선택지가 있지 않을까요?

2022-09-14 10:14 UTC, uk960214 commented on src/components/common/DropDownBox/DropDownBox.tsx
> +    <S.DropDownBox className={className} {...positions}>
`classname`은 무엇 때문에 필요한가요?

2022-09-14 10:14 UTC, uk960214 commented on src/components/pages/StoreDetailPage/StoreReviewItem/StoreReviewItem.style.tsx
> +  ${({ theme }) => css`
`theme`이 두 번 사용 되는 경우인 것 같은데 이 때 css 함수를 활용해서 지금과 같은 형태로 구현하는 것이 어느 정도의 효과가 있나요?

2022-09-14 10:14 UTC, uk960214 commented on src/components/pages/StoreDetailPage/StoreReviewItem/StoreReviewItem.style.tsx
> +  ${({ theme }) => css`
여기서는 `theme`이 사용되지 않네요??

2022-09-14 10:14 UTC, uk960214 commented on src/components/pages/StoreDetailPage/StoreReviewItem/StoreReviewItem.tsx
> +                    top="20px"
지금과 같이 20px 씩 위치를 조정해 준 이유가 있나요?

2022-09-14 10:14 UTC, uk960214 commented on src/components/pages/StoreDetailPage/StoreReviewItem/StoreReviewItem.tsx
> +            )}
이 부분으로 인해서 jsx 부분의 가독성이 확실하게 떨어지는 것 같은데 이를 해소할 수 있는 방법이 없을까요?

2022-09-14 10:16 UTC, uk960214 commented on src/components/pages/StoreDetailPage/StoreReviewItem/StoreReviewItem.tsx
> +            )}
이 부분으로 인해서 jsx 부분의 가독성이 확실하게 떨어지는 것 같은데 이를 해소할 수 있는 방법이 없을까요?

2022-09-19 06:09 UTC, liswktjs commented on src/components/pages/StoreDetailPage/StoreReviewItem/StoreReviewItem.tsx
> +            )}
재사용 할 것이 아니라, 지금 당장의 리팩토링은 불필요할것 같습니다

2022-09-19 06:10 UTC, liswktjs commented on src/components/pages/StoreDetailPage/StoreReviewItem/StoreReviewItem.tsx
> +                    top="20px"
원래의 사이즈가 있어서 이렇게 해야  적당한 위치에 오더라고요

2022-09-19 06:11 UTC, nan-noo commented on src/components/pages/StoreDetailPage/StoreReviewItem/StoreReviewItem.style.tsx
> +  ${({ theme }) => css`
두번 사용되니까 중복돼서 하나로 묶어줬습니다. 

${theme => theme.~~}를 두 번 사용하는 것보다는 낫지 않을까요?

2022-09-19 06:12 UTC, liswktjs commented on src/components/common/DropDownBox/DropDownBox.style.tsx
> +    ${right && `right: ${right};`}
위치를 커스텀해서 지정해줄 수 있어서 편하다고 생각합니다

2022-09-19 06:22 UTC, nan-noo approved these changes

2022-09-19 06:23 UTC, merged

2022-09-22 11:19 UTC, uk960214 commented on src/components/common/DropDownBox/DropDownBox.style.tsx
> +    ${right && `right: ${right};`}
정말 항상 모든 경우에 px 단위로 조정해줘야 할까요?