1.2.0 버전 배포 (랜덤 룰렛, UI 수정)
The-Fellowship-of-the-matzip/mat.zip-front pull request #144
Opened 2022-10-25 08:31 UTC by uk960214

1. 랜덤 룰렛 컴포넌트 홈 화면에 추가
    - 기존의 랜덤 API 활용, 메뉴 추천
    - CSS 애니메이션으로 룰렛 애니메이션 구현
    - 추후에 카테고리로 필터할 수 있는 API가 구현되면 변경할 예정
    - 별도의 hook으로 로직 분리, reducer 사용
2. 식당 목록에서 평균 별점을 정수 개의 별 이모티콘이 아니라 소수점을 포함한 실제 점수로 변경
    - 4.1점과 4.9점이 동일한 UI로 표시되는 문제 해결
    - 식당 목록에서는 실제 점수가 표시되도록 수정
#139, #141, #143 PR 참고

2022-10-25 14:26 UTC, liswktjs requested changes
역시 블링 코드가 전체적으로 깔끔하고 이해하기 쉽네요! 
몇가지 코멘트만 달았습니다! 확인해주세요

2022-10-25 14:26 UTC, liswktjs commented on src/components/pages/CategoryPage/CategoryPage.tsx
> +      refetchOnWindowFocus: false,
카테고리 정보와 같은 경우에는, 새롭게 받아올 필요가 없으니깐, false옵션을 주었군요 꼼꼼한 설정 👍

2022-10-25 14:26 UTC, liswktjs commented on src/components/pages/CategoryPage/RandomPick/RandomPick.tsx
> +  };
어떤 경우 때문에 resetHard 기능을 만들게 되었나요?

2022-10-25 14:26 UTC, liswktjs commented on src/components/pages/CategoryPage/RandomPick/RandomPick.tsx
> +      {isError && error instanceof Error && (
error instanceof Error로 한 번 더 확인해준 이유가 무엇인가요? 
혹시 사전에 약속된 에러가 오지 않았을 때를 대비한 것일까요? 🤔

2022-10-25 14:26 UTC, liswktjs commented on src/components/pages/CategoryPage/RandomPick/RandomPick.tsx
> +        </S.CustomButton>
해당 부분을 한 번 더 컴포넌트로 분리해도 괜찮을 것 같아요!

2022-10-25 14:26 UTC, liswktjs commented on src/components/pages/CategoryPage/RandomPick/reducer.ts
> +    };
오 Pick을 통해서 State관련해서 타입을 지정하고 뽑아서 사용하는 방식 좋네요 👍 저도 기억해뒀다가 써먹어야겠어요

2022-10-25 14:26 UTC, liswktjs commented on src/components/pages/CategoryPage/RandomPick/reducer.ts
> +export const reducer = (state: State, action: Action) => {
어떤 reducer인지 네이밍을 추가하는게 어떨까요?

2022-10-26 01:37 UTC, uk960214 commented on src/components/pages/CategoryPage/RandomPick/RandomPick.tsx
> +        </S.CustomButton>
이 부분은 이 컴포넌트의 가장 핵심적인 마크업 부분인 것 같아서 이대로 두는게 응집성 측면에서 좋을 것 같은데 어떻게 생각하시나요?

2022-10-26 01:49 UTC, uk960214 commented on src/components/pages/CategoryPage/RandomPick/reducer.ts
> +export const reducer = (state: State, action: Action) => {
반영했습니다! [`f9c09ad`](https://github.com/The-Fellowship-of-the-matzip/mat.zip-front/pull/144/commits/f9c09ad5589597be64109a392945549bd4631822)

2022-10-26 01:50 UTC, uk960214 commented on src/components/pages/CategoryPage/RandomPick/RandomPick.tsx
> +      {isError && error instanceof Error && (
사실 다른 컴포넌트에서 사용되는 것을 재활용한건데,
추측해보면 error.message를 전달하기 위해서는 error가 Error 객체여야 하기 때문에
타입스크립트 오류가 나는 것을 방지해주기 위해서 생긴 조치 같네요!

2022-10-26 04:00 UTC, liswktjs commented on src/components/pages/CategoryPage/RandomPick/RandomPick.tsx
> +        </S.CustomButton>
룰렛 컴포넌트로 나누어도 되지 않을까 싶어요!

2022-10-26 04:01 UTC, liswktjs approved these changes
바뀐 reducer이름이 역할을 명시하는데 더 좋네요! 
컴포넌트 분리는 좀 더 생각해봐요!

2022-10-26 04:01 UTC, liswktjs commented on src/components/pages/CategoryPage/RandomPick/randomRouletteStateReducer.ts
> +export const randomRouletteStateReducer = (state: State, action: Action) => {
👍

2022-10-26 04:03 UTC, merged