Issue164 리뷰 이미지 업로드 기능 추가
The-Fellowship-of-the-matzip/mat.zip-front pull request #165
Opened 2023-06-24 16:23 UTC by hafnium1923

#164 
@ashleysyheo 

- 리뷰 추가 시, 이미지도 업로드할 수 있다(optional + 한 개만 업로드 가능)

<img width="393" alt="Store Detail Page - Add Review" src="https://github.com/The-Fellowship-of-the-matzip/mat.zip-front/assets/51967731/5adbe39b-6660-43f0-b06f-a567bc0c5dbe">
<img width="393" alt="Store Detail Page - Add Review-1" src="https://github.com/The-Fellowship-of-the-matzip/mat.zip-front/assets/51967731/2dd2207f-d65f-4b1f-847e-7769e384321a">

<img width="393" alt="Store Detail Page" src="https://github.com/The-Fellowship-of-the-matzip/mat.zip-front/assets/51967731/53dd0b09-fa8a-4f4a-a808-a287894156cd">

2023-06-25 01:31 UTC, uk960214 reviewed
수고하셨습니다!

코드에 남긴 리뷰 외에도 기획과 UI 상 질문이 있는데요,
1. 이미지는 하나만 추가할 수 있던데 혹시 여러 개의 이미지를 추가하는 기능에 대해서는 계획이 없으신가요?? 만약에 계획은 있는데 지금은 구현이 안된 것이라면 imageUrl 타입을 배열로 받는 것은 어떨까 하는 생각도 했습니다.
2. 이미지를 하나 밖에 업로드할 수 없지만 현재 UI 상으로는 여러 개 올릴 수 있는 것 같은 느낌이더라구요. 만약에 이미지를 수정하는 것을 가능하게 하기 위해서 현재 UI (버튼과 이미지가 같이 보이는 것)을 구성한거라면, 혹시 업로드한 이미지를 지우고 (x 버튼처럼), 다시 업로드 버튼을 보여주는 방식은 어떠신가요?
![KakaoTalk_20230625_103014077](https://github.com/The-Fellowship-of-the-matzip/mat.zip-front/assets/43166681/30cd03ca-7d52-4bf4-bc87-c1428d345748)
3. 업로드 된 이미지의 스타일이 좀 심심한 것 같아요! 혹시 border-radius 정도는 넣을 생각은 안해보셨나요??

2023-06-25 01:31 UTC, uk960214 commented on src/hooks/useImageUpload.ts
> +      alert("이미지 업로드에 실패했습니다.");
여기 메시지에도 '다시 시도해주세요.'와 같은 말을 덧붙인다면 훨씬 친절하게 느낄 것 같아요!

2023-06-25 01:31 UTC, uk960214 commented on src/hooks/useImageUpload.ts
> +      const imageUrl = data?.imageUrl;
data가 null 이나 undefined로 올 가능성이 있나요? 있다면 어떤 케이스에 오는 것일까요? 없다면 옵셔널체이닝은 불필요하지 않을까요? 타입을 잘 구성해서 sendImageUploadPostRequest 함수가 imageUrl을 포함한 data를 반환하는 것으로 한다면, data에서 바로 구조분해 할당까지 할 수 있을 것도 같습니다. 어떻게 생각하시나요?

2023-06-25 01:31 UTC, uk960214 commented on src/components/common/Star/Star.style.tsx
> +      height: 16px;
요거는 커밋이 '버그수정'으로 되어있던데 혹시 따옴표가 css에 포함되서 오류가 생겼었나요??

2023-06-25 01:31 UTC, uk960214 commented on src/components/common/ImageUploadInput/ImageUploadInput.tsx
> +  const uploadButtonClick = () => {
요 변수명만 보았을 때는 함수인지 핸들러인지 어떤 역할을 하는 것인지 확실히 알 수 없을 것 같은데, handle, handler라던가 on~을 사용해서 명확히 이벤트 핸들러임을 나타내는 것은 어떻게 생각하시나요?

2023-06-25 10:36 UTC, ashleysyheo commented on src/components/common/Star/Star.style.tsx
> +      height: 16px;
넵! 따옴표를 추가했을 때 실제 css에도 따옴표가 추가된 상태로 값이 들어가서 유효하지 않은 값이라는 에러가 떠서 수정했습니다.

2023-06-25 10:44 UTC, ashleysyheo commented on src/components/pages/StoreDetailPage/StoreReviewItem/StoreReviewItem.style.tsx
> +  object-position: left top;
지금 `ReviewContentWrapper`에서 `display: flex`가 설정되어 있어서, 각 자식(?)들이 전체 `width`를 차지하고 있습니다. 그래서 이미지의 `width`가 자동으로 전체 너비를 차지하기 때문에 사진이 찌그러지는 문제가 발생해서 `object-position`을 추가했습니다!

> 업로드 된 이미지의 스타일이 좀 심심한 것 같아요! 혹시 border-radius 정도는 넣을 생각은 안해보셨나요??

원래는 `border-radius`를 추가하고 싶었습니다...!

그런데 `object-fit`으로 비율을 조절하고 있기 때문에 `img`의 실제 너비는 전체 `width`가 되어서 `border-radius`를 설정하면 왼쪽 위아래만 적용되는 문제가 발생해서 일단 뺐습니다. 이 부분을 어떻게 해결하면 좋을지 생각해 내지 못해서 일단 `border-radius`를 뺐습니다.

2023-06-25 10:53 UTC, ashleysyheo commented on src/hooks/useImageUpload.ts
> +      const imageUrl = data?.imageUrl;
`sendImageUploadPostRequest`가 무조건 이미지 응답 데이터 형식으로 리턴하기 때문에 `null`이나 `undefined`로 올 가능성이 전혀 없네요... 처음에 작업할 때 구조 분해 할당을 하니까 린트 에러가 떠서 저렇게 작성했었는데, 다시 해 보니까 에러가 안 뜨네요...!
바로 구조 분해 할당 하는 방식으로 수정했습니다!

2023-06-25 11:10 UTC, hafnium1923 commented on src/components/common/ImageUploadInput/ImageUploadInput.tsx
> +  const uploadButtonClick = () => {
onClick 이벤트에 사용할 핸들라서 이름 끝에 Click이라는 접미사를 붙였습니다. 보통 함수들에는 Click이라는 이름을 붙이지 않기 때문에 충분히 이벤트 핸들러라는 것을 나타낼 것이라고 생각했거든요! 그럼에도 바꾸는 것이 좋을까요?

2023-06-25 15:45 UTC, uk960214 commented on src/components/common/ImageUploadInput/ImageUploadInput.tsx
> +  const uploadButtonClick = () => {
정말 진지하게 고민해보자면 컨벤션으로 정하는 것이 좋아보이기는 합니다! 보통 함수들에 click을 붙여주지 않는 것은 맞긴 하지만 그렇다고 붙일 수 없는 것은 또 아니니까요! 😀

2023-06-25 15:57 UTC, uk960214 commented on src/components/pages/StoreDetailPage/StoreReviewItem/StoreReviewItem.style.tsx
> +  object-position: left top;
<img src="https://github.com/The-Fellowship-of-the-matzip/mat.zip-front/assets/43166681/cf28a67f-95f5-44ba-8acb-8f7d47ace28d" width="300" />
<img src="https://github.com/The-Fellowship-of-the-matzip/mat.zip-front/assets/43166681/183ef729-fcfc-436a-8df7-fc80ad9b5e13" width="500" />

flex일 때 전체 너비를 차지하는 문제는 정렬을 기본값이라도 주게 되면 자체 너비를 가지게 되어서 해결됩니다!
이렇게 바꾸면 object fit, position으로 해결하지 않아도 되고 border radius, shadow등 원하는 대로 스타일을 줄 수 있을 것 같네요!

2023-06-26 14:25 UTC, ashleysyheo commented
### 이미지 여러 개 추가 관련

백엔드랑 얘기해 봤는데, 여러 개를 추가할 수 있도록 하려면 많이 변경해야 해서 당장은 계획이 없다고 합니다! 그런데 여러 개를 업로드할 수 있는 게 더 자연스럽다고 동의해서 추후에 논의해 볼 예정입니다.

### 이미지 업로드 UI 
블링이 말한 것처럼 여러 개를 올릴 수 있다는 느낌이 들긴 드네요... 아직까지는 이미지를 여러 개 업로드할 수 있게 할 계획이 없기 때문에 제안해 주신 것처럼 변경해 봤습니다!

<img width="482" alt="Screenshot 2023-06-26 at 11 19 08 PM" src="https://github.com/The-Fellowship-of-the-matzip/mat.zip-front/assets/51967731/af38a004-0c99-4413-afbb-4ccbe81c77ea">

2023-06-26 15:06 UTC, liswktjs approved these changes
변경사항 확인하였습니다!

2023-06-26 15:06 UTC, liswktjs commented on src/hooks/useImageUpload.ts
> +      alert("이미지 업로드에 실패했습니다.");
혹시 이 멘트는 바꾸지 않고 그대로 하나요?

2023-06-26 16:57 UTC, uk960214 commented
이미지 업로드 UI에서 x 버튼 추가된 것은 아주 좋은 것 같아요! 개인적인 취향이지만 아이콘 버튼에 이미지와 동일한 radius가 들어가고 코너에 딱 맞춰져 있어서 살짝 어색한 느낌이 드는데 혹시 버튼에는 radius를 없앤다거나 position을 코너에 딱 맞지 않게 해서 x 버튼이 좀 더 눈에 띄게 만드는 것은 어떻게 생각하시나요?
![image](https://github.com/The-Fellowship-of-the-matzip/mat.zip-front/assets/43166681/16dcd063-95df-4ad7-99ff-8c602cf748c8)

+ 이미지를 삭제하고 다시 업로드 하려고 하면 안되는 버그가 있네요! 어째서인지 지우고 다시 업로드하면 images를 호출하지 않아요!

2023-06-27 10:34 UTC, ashleysyheo commented
#### 삭제 버튼 ui
x 버튼에 margin을 주는 것을 고려했는데 실제로 한 4px 정도의 간격을 주니까 뭔가 어색한 느낌이 들더라고요!

<img width="118" alt="Screenshot 2023-06-27 at 7 31 41 PM" src="https://github.com/The-Fellowship-of-the-matzip/mat.zip-front/assets/51967731/3479f8f5-fdfc-4e3b-89ef-98021de51bfa">

그래서 한 번 전체에 border-radius를 주는 대신 border-top-right-radius만 이미지 border-radius랑 맞춰봤습니다. 그리고 버튼 색상도 진회색이 아니라 블랙으로 변경해서 조금 더 눈에 띌 수 있도록 수정했습니다!

<br>

>  지금 가게 상세 페이지를 들어가면 기본으로 리뷰 작성창이 떠있고 꺼지지 않아요. 아마도 개발 시 편의를 위해서 렌더링 조건을 반대로 해놓은 것 같은데 되돌려야 할 것 같아요!

앗.... 완전 깜빡했어요! 되돌려놨습니다!

<br>

> 이미지를 삭제하고 다시 업로드 하려고 하면 안되는 버그가 있네요! 어째서인지 지우고 다시 업로드하면 images를 호출하지 않아요!

이미지를 삭제하고 다시 업로드 하려고 하면 안되는 상황이 정확히 어떤건가요...? 제가 했을 때는 삭제하고 재업로드가 잘 되거든요.

https://github.com/The-Fellowship-of-the-matzip/mat.zip-front/assets/51967731/9eed7022-e4f0-40d5-a12c-c49a4b4f4a87

2023-06-27 10:36 UTC, ashleysyheo commented on src/hooks/useImageUpload.ts
> +      alert("이미지 업로드에 실패했습니다.");
`이미지 업로드에 실패했습니다. 다시 시도해 주세요.`로 변경했습니다!

2023-06-27 12:29 UTC, nan-noo requested changes
리뷰 남겼습니다!

저도 블링이랑 똑같은 오류 나요!

> https://github.com/The-Fellowship-of-the-matzip/mat.zip-front/assets/54002105/7d270a67-f362-452c-8d2f-66038ca9b6e2

그리고 인풋 크기 고정하면 어떨까요? 화면 밖으로 튀어나가서..!
> ![화면 캡처 2023-06-27 210958](https://github.com/The-Fellowship-of-the-matzip/mat.zip-front/assets/54002105/b91e953a-e490-4562-ab6b-1bd5af75d42f)

2023-06-27 12:29 UTC, nan-noo commented on src/api/image/sendImageUploadPostRequest.ts
디렉토리명 > image보다 더 구체적으로 정하면 어떨까요?
review 디렉토리에 넣지 않고 image를 새로 만든 이유가 있을까요?

2023-06-27 12:29 UTC, nan-noo commented on src/api/image/sendImageUploadPostRequest.ts
> +  }
accessToken 검증해서 존재할 때만 요청보내는 게 일부 api에서 공통된 로직일 것 같은데, axios interceptor를 활용해보는 건 어떨까요?

2023-06-27 12:29 UTC, nan-noo commented on src/api/image/sendImageUploadPostRequest.ts
> +  const response: AxiosResponse<ImageUploadResponse> = await axiosInstance.post(
```ts
 post<T = any, R = AxiosResponse<T>, D = any>(url: string, data?: D, config?: AxiosRequestConfig<D>): Promise<R>;
```
제네릭으로 응답타입을 정할 수도 있어요!

2023-06-27 12:29 UTC, nan-noo commented on src/api/image/sendImageUploadPostRequest.ts
> +        Authorization: `Bearer ${accessToken}`,
일부 api에 공통된 헤더일 것 같은데 매번 쓰지 않고 api 요청 보내기 전에 미리 처리하는 방법이 있지 않을까요?

2023-06-27 12:29 UTC, nan-noo commented on src/components/common/ImageUploadInput/ImageUploadInput.style.ts
> +  background-color: ${({ theme }) => theme.color.black};
비슷한 것끼리 묶고 간격을 띄우는 건 어떨까요?

2023-06-27 12:29 UTC, nan-noo commented on src/components/common/ImageUploadInput/ImageUploadInput.style.ts
> +  }
왜 여기에선 props를 활용하지 않고 className을 사용했나요?

2023-06-27 12:29 UTC, nan-noo commented on src/components/common/ImageUploadInput/ImageUploadInput.style.ts
> +  transition-property: background-color, border, outline !important;
!important가 꼭 필요한가요? 뭔가 제가 보기엔 별 차이 없어보여서..

2023-06-27 12:29 UTC, nan-noo commented on src/components/common/ImageUploadInput/ImageUploadInput.tsx
> +import { Label } from "../Label/Label.style";
절대경로랑 상대경로 어떻게 생각하세요??

2023-06-27 12:29 UTC, nan-noo commented on src/components/common/ImageUploadInput/ImageUploadInput.tsx
> +  imageUrl: string | null;
imageUrl 타입으로 optional이 아니라 null을 썼네요! 의도한건가요?

2023-06-27 12:29 UTC, nan-noo commented on src/components/common/ImageUploadInput/ImageUploadInput.tsx
> +          name="image-upload"
image-upload가 세 번 반복되니까 파일 내에 분리하면 좋을 것  같아요!

2023-06-27 12:29 UTC, nan-noo commented on src/components/common/ImageUploadInput/ImageUploadInput.tsx
> +            <S.UploadedImage src={imageUrl} alt="리뷰 이미지" />
공통 컴포넌트인데 alt가 리뷰 이미지로 고정되어서 재활용하기 어려울 것 같아요! alt도 props로 받는 건 어떨까요?

2023-06-27 12:29 UTC, nan-noo commented on src/hooks/useImageUpload.ts
> +      alert("이미지 업로드에 실패했습니다. 다시 시도해 주세요.");
나중에 alert나 confirm 말고 커스텀 컴포넌트 만들어보는 건 어때요??ㅎㅎ

2023-06-27 12:29 UTC, nan-noo commented on src/mock/handlers/index.ts
> +import { imageHandler } from "./imageHandler";
얘만 상대경로네요!

2023-06-28 12:22 UTC, ashleysyheo commented on src/api/image/sendImageUploadPostRequest.ts
이미지 api 자체를 재사용할 수 있게 만들기 위해서 리뷰를 보낼 때 이미지 파일 데이터를 보내서 imageUrl을 생성하는 것이 아닌 별도의 api를 만들었다고 백엔드한테 들었습니다. 그런 의미에서 추후에 이 api가 리뷰가 아닌 다른 상황에서 사용될 것을 생각하면 images를 만드는 것이 좀 더 어울리지 않나 싶어서 그렇게 했습니다!

2023-06-28 12:29 UTC, ashleysyheo commented on src/components/common/ImageUploadInput/ImageUploadInput.style.ts
> +  transition-property: background-color, border, outline !important;
필요없어요...! 거기에다가 이미지 추가한 후에는 이미지 추가 버튼을 없애고 이미지 삭제 버튼을 추가하면서 `transition-property` 자체가 필요없어져서 삭제했습니다.

2023-06-28 12:33 UTC, ashleysyheo commented on src/components/common/ImageUploadInput/ImageUploadInput.tsx
> +import { Label } from "../Label/Label.style";
크게 생각해 본 적이 없네요...! 🤔

평소에 그냥 vscode import 자동완성을 사용해서 크게 신경쓰지 않고 그대로 사용했어요. 보통은 절대 경로를 많이 사용하나요??

2023-06-28 12:34 UTC, ashleysyheo commented on src/components/common/ImageUploadInput/ImageUploadInput.tsx
> +  imageUrl: string | null;
네 의도했습니다!

백엔드에서 이미지가 없을 때는 `null`값을 보내준다고 해서 `null` 타입을 추가했습니다.

2023-06-28 12:44 UTC, ashleysyheo commented on src/hooks/useImageUpload.ts
> +      alert("이미지 업로드에 실패했습니다. 다시 시도해 주세요.");
안 그래도 confirm이나 alert를 대화 상자(?)를 default를 사용하고 있어서 커스텀 컴포넌트를 만들고 싶었어요! 이번에 마무리한 다음에 만들어 보겠습니다!

2023-06-28 13:23 UTC, ashleysyheo commented on src/api/image/sendImageUploadPostRequest.ts
> +  }
```js
const checkAccessToken = (config: AxiosRequestConfig) => {
  if (!config.headers || !Object.hasOwn(config.headers, "Authorization")) {
    return config;
  }

  const accessToken = window.sessionStorage.getItem(ACCESS_TOKEN_KEY);

  if (!accessToken) {
    window.sessionStorage.removeItem(ACCESS_TOKEN_KEY);
    window.alert("다시 로그인 해주세요");
    window.location.reload();
    throw new Error("엑세스토큰이 유효하지 않습니다");
  }

  config.headers.Authorization = `Bearer ${accessToken}`;

  return config;
};

axiosInstance.interceptors.request.use(checkAccessToken, handleAPIError);
```

이런 식으로 interceptor를 사용해서 공통된 로직을 분리한다는 말일까요??

> accessToken이 필요한 모든 함수에서 sessionStorage에 매번 접근하는 것도 비효율적인 것 같아보이네요.. 가능하면 공통화하고 런타임에서 들고 있는 것도 좋아보입니다!

블링도 다른 PR에서 이런 피드백을 줬는데, 이 부분은 새로운 이슈를 만들어서 리팩토링해 보겠습니다!

2023-06-28 13:39 UTC, ashleysyheo commented on src/api/image/sendImageUploadPostRequest.ts
> +        Authorization: `Bearer ${accessToken}`,
지금으로서 생각나는 방법은 authorization 용 axiosInstance를 하나 더 만들면서 거기에 headers를 추가하는 방법이 있을 것 같아요.

api 관련된 리팩토링은 위에 말한 것처럼 새로운 이슈를 만들어서 리팩토링해 보겠습니다!

2023-06-29 12:41 UTC, ashleysyheo commented on src/components/common/ImageUploadInput/ImageUploadInput.style.ts
> +  }
Button 컴포넌트를 만들어 둔 common 컴포넌트를 사용한 다음에 `css`를 props로 넘겨주고 있기 때문에 추가적으로 props를 넘기는 부분이 애매해져서 className을 사용했습니다!

2023-06-29 12:47 UTC, ashleysyheo commented on src/components/common/ImageUploadInput/ImageUploadInput.tsx
> +          name="image-upload"
id나 name과 같은 input 태그 기본 attribute도 props로 받는 방법으로 수정했습니다! 나중에 ImageUploadInput이 여러 개 있다면 id가 겹치면 안 되니까요.

2023-06-29 12:56 UTC, ashleysyheo commented on src/api/image/sendImageUploadPostRequest.ts
> +  const response: AxiosResponse<ImageUploadResponse> = await axiosInstance.post(
그렇군요...!

그럼 제네릭으로 응답타입을 정한다면 이렇게 하는 건가요?

```js
const sendImageUploadPostRequest = async <T>(imageFile: File) => {

  // ...

  const response: AxiosResponse<T> = await axiosInstance.post(
    ENDPOINTS.IMAGE_UPLOAD,
    imageFile,
    {
      headers: {
        Authorization: `Bearer ${accessToken}`,
        "Content-Type": "multipart/form-data",
      },
    }
  );

  return response.data;
};
```

<br>

그런데, 지금과 같이 api에 대해서는 응답 값 형태(?)가 정해져 있을 때는 보통 제네릭을 사용해서 위 api 함수를 사용하는 측에서 타입을 명시하나요 아니면 api 함수 자체에서 response 타입을 명시하는 편인가요?

2023-06-29 13:03 UTC, ashleysyheo commented
@nan-noo 

> 저도 블링이랑 똑같은 오류 나요!

엇 왜죠... 🥲 혹시 accessToken 여부를 검증하는 로직 때문에 오류가 나는 거 아닐까요....??


```
POST /api/images HTTP/1.1

Header
Authorization: Bearer {access_token}

Body
file : multiPart/form-data
```

지금 위처럼 이미지 api에서도 accessToken을 보내야 해서 msw로 확인할 때 `sendImageUploadPostRequest`에서 accessToken 여부를 검증하는 부분을 코멘트 처리해야 제대로 확인할 수 있습니다. 한 번 확인 부탁드려요!

<br>

> 그리고 인풋 크기 고정하면 어떨까요? 화면 밖으로 튀어나가서..!

이것도 제 컴퓨터에서는 안 보여서 몰랐어요 🥲 일단, `textarea`에 `max-width`를 추가했는데, 아직도 튀어나오나요??

2023-06-29 14:50 UTC, uk960214 commented on src/api/image/sendImageUploadPostRequest.ts
> +  const response: AxiosResponse<ImageUploadResponse> = await axiosInstance.post(
아 요건 post 함수에 대한 제네릭을 말하는걸거에요!
그러니까 await axiosInstance.post<T>(...)가 되는거겠죠!

> 제네릭을 사용해서 위 api 함수를 사용하는 측에서 타입을 명시하나요 아니면 api 함수 자체에서 response 타입을 명시하는 편인가요?

제가 정확히 이해한건지 모르겠는데 제네릭은 사용처에 따라서 타입을 여러가지로 받아서 활용해야 할 때 사용하니까, 굳이 이런 과정이 필요하면 제네릭이 아예 필요 없을 것이고, 제네릭을 사용하는 경우라면 당연히 사용처에서 타입을 지정해주는 것이 맞겠죠?

2023-06-29 14:54 UTC, uk960214 commented on src/components/common/ImageUploadInput/ImageUploadInput.style.ts
> +  }
음 이 부분은 생각보다 스타일을 주는 방식이 너무 섞여있는거일 수도 있겠네요!
기존 버튼에도 스타일이 있을 거고, css 문자열로 받는 것도 있고, 클래스에 따른 네이티브와 같은 css도 있으니까요!
요걸 조금 더 단순한 방법으로 정리할 수는 없을까요?
예를 들어 css 문자열을 반환하는 함수를 만들고 uploaded 여부는 인자로 받는다거나..?

2023-06-29 14:54 UTC, uk960214 commented on src/components/common/ImageUploadInput/ImageUploadInput.tsx
> +import { Label } from "../Label/Label.style";
정하기 나름이긴 하죠! 장단점을 고민해볼 필요는 있다고 봅니다!

2023-06-29 14:58 UTC, uk960214 commented
오 저는 두 문제 다 이제는 해결된 것 같네요! 수고하셨습니다!

2023-06-29 14:58 UTC, uk960214 approved these changes

2023-06-30 07:10 UTC, nan-noo reviewed
저 이미지 업로드 오류가 발생하는 상황이, A 사진을 업로드 하고 삭제한 다음 다시 A 사진을 업로드하면 발생합니다! A 사진 업로드하고 B 사진 업로드하는 건 잘 돼용

텍스트아리아 삐져나오는 건 오른쪽 아래 늘리는 버튼 막아달라는 이야기였어요!!
> 
![image](https://github.com/The-Fellowship-of-the-matzip/mat.zip-front/assets/54002105/86c05629-847e-4338-885c-baf411170120)

2023-06-30 07:10 UTC, nan-noo commented on src/components/common/ImageUploadInput/ImageUploadInput.tsx
> +import { Label } from "../Label/Label.style";
각각 장단점이 있어요! 근데 저는 상대경로가 복잡해지면 어디에 속하는지 파악하기가 import문 정리할 때 어려워서 절대경로로 통일하는 편이에요

2023-06-30 07:10 UTC, nan-noo commented on src/api/image/sendImageUploadPostRequest.ts
> +  const response: AxiosResponse<ImageUploadResponse> = await axiosInstance.post(
블링이 잘 대답해줬는데, 제가 말한 건 axios가 제공하는 메서드에 제네릭으로 response 타입이나 request body 타입 등등을 지정할 수 있다는 말이었어요!

```ts
const response: AxiosResponse<ImageUploadResponse> = await axiosInstance.post<타입들...>(...)
```

제네릭은 필요하다면(내부에서 쓸 타입을 외부에서 주입해야 하는 상황(?) 등등) 쓰고 필요하지 않으면 안 써도 돼용

2023-06-30 07:10 UTC, nan-noo commented on src/components/common/ImageUploadInput/ImageUploadInput.style.ts
> +  }
스타일 적용하는 방식을 줄이는 게 좋을 것 같아요! 블링이 말한 함수 활용도 좋네요

2023-06-30 07:10 UTC, nan-noo commented on src/api/image/sendImageUploadPostRequest.ts
아하 그러면 한 api로 모든 종류의 이미지 업로드를 다루는건가요?? 아니면 나중에 /image/review 식으로 세부적으로 나뉘나요?

2023-07-01 16:17 UTC, ashleysyheo commented on src/api/image/sendImageUploadPostRequest.ts
제가 이해하기로는 이 images api로 모든 종류의 이미지 업로드를 다 다룬다고 알고 있습니다! 그래서 백엔드 쪽에서도 리뷰 폼을 제출할 때 이미지 파일 데이터를 보내는 것이 아니라, 일차적으로 이미지 url을 요청한 다음에 그 url을 리뷰 보낼 때 함께 보내도록 만든 것 같아요.

2023-07-01 16:30 UTC, ashleysyheo commented
@nan-noo 
> 저 이미지 업로드 오류가 발생하는 상황이, A 사진을 업로드 하고 삭제한 다음 다시 A 사진을 업로드하면 발생합니다! A 사진 업로드하고 B 사진 업로드하는 건 잘 돼용

찾아보니까 `onChange` 이벤트가 실질적으로 파일 데이터가 바뀔 때만 반응해서 `event.target.value`를 초기화 시켜주는 코드를 추가했습니다! 

> 텍스트아리아 삐져나오는 건 오른쪽 아래 늘리는 버튼 막아달라는 이야기였어요!!
아 이 얘기였군요!! ㅎㅎ `resize` 막았습니다!

2023-07-01 16:35 UTC, ashleysyheo commented on src/components/common/ImageUploadInput/ImageUploadInput.style.ts
> +  }
>  예를 들어 css 문자열을 반환하는 함수를 만들고 uploaded 여부는 인자로 받는다거나..?

이런 방법이 있었네요! `isUploaded` 여부를 인자로 받은 다음에 css를 반환하는 방식으로 변경해 봤습니다.

2023-07-03 03:40 UTC, nan-noo approved these changes

2023-07-03 10:05 UTC, merged