Issue162 음식점 북마크 기능 추가
The-Fellowship-of-the-matzip/mat.zip-front pull request #167
Opened 2023-06-25 11:55 UTC by hafnium1923

- 카테고리 페이지, 음식점 목록 페이지, 그리고 음식점 상세 페이지에서 음식점 저장/삭제할 수 있는 기능 추가
- 카테고리 페이지, 음식점 목록 페이지에서 로그인 되어 있을 때는 북마크 표시가 보이고, 아닌 상태에는 아웃라인 하트 아이콘을 볼 수 있다
  -  로그인 안 했을 때 음식점을 저장하려고 하면 로그인 해라는 메세지가 나타난다

<img width="393" alt="Category Page" src="https://github.com/The-Fellowship-of-the-matzip/mat.zip-front/assets/51967731/42627842-5a50-4706-a436-9ef2fbb3c554">

<img width="393" alt="Search Result Page" src="https://github.com/The-Fellowship-of-the-matzip/mat.zip-front/assets/51967731/9e263dea-1711-4828-8da0-baa42c5153d7">

<img width="393" alt="Store Detail Page" src="https://github.com/The-Fellowship-of-the-matzip/mat.zip-front/assets/51967731/e6a44ada-d7a5-48ee-bbe1-a1bc4986adab">

2023-06-25 16:13 UTC, uk960214 commented on src/api/bookmark/sendBookmarkDeleteRequest.ts
> +  }
유사한 오류 처리 로직을 전에도 어디선가 본 것 같은데 이건 공통화 하는게 어떨까요?

2023-06-25 16:13 UTC, uk960214 commented on src/api/store/fetchRandomStoreList.tsx
> +    accessToken ? userFetchOptions : undefined
사용자가 로그인한지 여부에 따라서 옵션을 다르게 주려고 한 것이 맞을까요?
만약 그렇다면 공통적으로 사용될 옵션이 추가되었을 때에는 어떤 식으로 코드가 바뀔지, 어떻게 하면 옵션이 추가되어도 변경이 어렵지 않을지 고민해보면 좋을 것 같아요!

2023-06-25 16:13 UTC, uk960214 commented on src/api/store/fetchRandomStoreList.tsx
> +  const accessToken = sessionStorage.getItem(ACCESS_TOKEN);
기존 코드에도 있었지만 갑자기 생각난 것 중 하나인데, accessToken이 필요한 모든 함수에서 sessionStorage에 매번 접근하는 것도 비효율적인 것 같아보이네요.. 가능하면 공통화하고 런타임에서 들고 있는 것도 좋아보입니다!

2023-06-25 16:13 UTC, uk960214 commented on src/components/common/StoreList/StoreList.tsx
> +            saved={store.saved}
북마크.. 기능이 맞긴한데요
사용하는 아이콘도 하트이다보니 saved 보다 뭔가 liked가 더 잘 어울리는 것 같기도 하네요..
요건 바꾸라는 것은 아니고 그냥 개인적인 감상입니다!

2023-06-25 16:13 UTC, uk960214 commented on src/hooks/useBookmark.ts
> +    },
요 부분이 저장 시에 오류가 발생하면 새로고침을 해주는 그 부분이 맞을까요? 새로고침이 추가된 이유는 optimistic 하게 하트를 채워줬다가 그걸 초기화하기 위해서일까요? 그렇다면 onError에서 다시 반대로 돌리는 setState를 해주는 것으로는 불가능했는지 궁금합니다!

2023-06-26 08:38 UTC, hafnium1923 commented on src/api/bookmark/sendBookmarkDeleteRequest.ts
> +  }
원래 있던 로직을 재사용하고 있기때문에 자주 보신 듯 합니당..ㅎㅎ 현재 기능 구현이 우선이라고 생각되기 때문에 기능 구현 완료 후 리팩터링 단계에서 공통화 해보도록 하겠습니다!

2023-06-26 08:41 UTC, hafnium1923 commented on src/api/store/fetchRandomStoreList.tsx
> +    accessToken ? userFetchOptions : undefined
넵 맞습니다. 나중에 옵션이 추가되면 fetchReviewList의 로직과 비슷하게 하면 될 것 같다고 생각하는데 제가 이해한게 틀렸다면 다시 설명해주실 수 있을까요?

2023-06-26 08:42 UTC, hafnium1923 commented on src/api/store/fetchRandomStoreList.tsx
> +  const accessToken = sessionStorage.getItem(ACCESS_TOKEN);
이또한 기능 구현완료 후 리팩터링 단계에서 공통화 해보도록 하겠습니다!

2023-06-26 08:43 UTC, hafnium1923 commented on src/components/common/StoreList/StoreList.tsx
> +            saved={store.saved}
처음 saved라고 지었던 이유가 내가 찜한, 혹은 내가 선택한 가게 라고 생각해서 직역해서 사용했습니다. 근데 개발하다보니 liked가 더 어울리는 것 같긴합니다ㅋㅋㅎㅎ..

2023-06-26 08:54 UTC, ashleysyheo commented on src/hooks/useBookmark.ts
> +    },
`onMutate`를 사용해서 변경할 당시의 북마크 상태를 리턴 한 다음에, `onError`에서 `context` 값을 사용해서 반대로 돌려주는 방식으로 수정해 봤습니다! alert는 그대로 뒀습니다!

2023-06-26 14:29 UTC, ashleysyheo commented on src/components/common/StoreList/StoreList.tsx
> +            saved={store.saved}
백엔드랑 얘기했을 때 liked는 저장의 의미를 크게 나타내는 것 같지 않다는 의견을 받았습니다. saved가 아니면 bookmarked로 명명하는 것을 제의했는데, 블링은 어떻게 생각하시나요?!

2023-06-26 15:12 UTC, liswktjs approved these changes
수고하셨습니다 나머지는 블링이 언급하고 있어서 에러처리 관련 코멘트를 남겼습니다! 
다만 에러바운더리와같은 경우에는 지금 당장 도입하기에는 난이도가 있을 것 같아서 그냥 이런게 있다 라는 것 정도만 알아도 좋을 것 같습니다 👍

2023-06-26 15:12 UTC, liswktjs commented on src/api/bookmark/sendBookmarkPostRequest.ts
> +
delete request와 error 날때 대응이 같아서 에러바운더리를 활용하여서 공통된 케이스들에 대해서는  중복없이 처리하는 것이 어떨지 제안해봅니다!

2023-06-26 16:46 UTC, uk960214 commented on src/components/common/StoreList/StoreList.tsx
> +            saved={store.saved}
글쎄요 그러면 도리어 아이콘을 하트가 아닌 북마크나 별표처럼 다른걸로 바꾸는게 더 자연스러우려나요? 하트와 saved가 어색하다는 생각입니다!

2023-06-26 17:16 UTC, uk960214 commented on src/api/store/fetchRandomStoreList.tsx
> +    accessToken ? userFetchOptions : undefined
그 방법도 좋은 것 같아요! 제가 또 떠올렸던 것은 config의 위치에 리터럴로 객체를 추가해서 공통적인 요소는 항상 있고, 조건에 따라 추가되는 것은 그 밑에 조건에 따라서 추가되도록 하는 방법이긴 했습니다! 취향의 영역이니 선택은 존중합니다!

2023-06-27 13:14 UTC, nan-noo requested changes

2023-06-27 13:14 UTC, nan-noo commented on README.md
리드미 수정이 요 PR에 있네요 👀

2023-06-27 13:14 UTC, nan-noo commented on src/api/bookmark/sendBookmarkDeleteRequest.ts
> +    window.alert("다시 로그인 해주세요");
로그인 안 하고 클릭했을 때 뜨는 오류 문구에서 '다시'가 어색한 것 같습니다! 그냥 '로그인해 주세요'가 좋을 것 같아요 :D

2023-06-27 13:14 UTC, nan-noo commented on src/api/store/fetchStoreList.tsx
> +    accessToken === null ? nonUserFetchOptions : userFetchOptions
여기는 왜 아래같이 안 하고 null과 같을 때를 명시했나요?
```ts
    accessToken ? userFetchOptions : nonUserFetchOptions
```

2023-06-27 13:14 UTC, nan-noo commented on src/components/common/StoreList/StoreList.tsx
> +            saved={store.saved}
저도 saved할거면 북마크가 더 어울리는 것 같아요! 하트나 엄지척은 liked가 맞을 것 같고..!

2023-06-27 13:14 UTC, nan-noo commented on src/hooks/useBookmark.ts
> +      alert("오류가 발생했습니다. 잠시 후 다시 시도해주세요.");
'다시 로그인해주세요' 다음에 바로 오류가 발생했습니다. '오류가 발생했습니다. 잠시 후 다시 시도해주세요' 경고창이 뜹니다! '다시 로그인해주세요' 경고창이 뜨면 후자가 나오면 안되는데 로직이 잘못된 것 같아요
axios에서 로그인 여부를 확인하고 에러를 throw하기때문에, react-query에서 또 잡아내는 것 같습니다!

2023-06-27 13:14 UTC, nan-noo commented on src/hooks/useBookmark.ts
> +    bookmark ? deleteBookmark.mutate() : postBookmark.mutate();
사용자가 굉장히 빠르게 하트 클릭을 반복할 때마다 요청이 가는데, debounce를 활용하는 건 어떨까요?

2023-06-27 13:14 UTC, nan-noo commented on src/components/pages/StoreDetailPage/StoreDetailTitle/StoreDetailTitle.tsx
> +  const { bookmark, handleBookmark } = useBookmark(id, saved);
bookmark는 명산데 타입이 boolean이라 어색해요! bookmarked나 marked, isMarked는 어떤가요?

2023-06-27 13:14 UTC, nan-noo commented on src/components/common/StoreListItem/StoreListItem.tsx
> +      <S.ListItemBookmark onClick={handleBookmark}>
북마크 요소를 div로 한 이유가 있을까요? 클릭이 가능한 대상은 버튼이나 인풋(check)으로 하는 게 어떨까요?

2023-06-30 00:49 UTC, hafnium1923 commented on src/components/common/StoreList/StoreList.tsx
> +            saved={store.saved}
백엔드에게 필드명 saved -> liked로 변경 요청드렸습니다. 바뀐 필드명으로 수정하겠습니다.

2023-06-30 00:54 UTC, hafnium1923 commented on src/api/bookmark/sendBookmarkPostRequest.ts
> +
네! 그래서 이슈 만들어놨습니다. 기능구현 끝나고 시간나는대로 짬짬히 대공사하려구요

2023-06-30 00:55 UTC, hafnium1923 commented on README.md
앗.... 간단하다고 생각해서 추가했는데 다시 삭제하도록 할까요,,,?

2023-06-30 00:55 UTC, hafnium1923 commented on src/api/bookmark/sendBookmarkDeleteRequest.ts
> +    window.alert("다시 로그인 해주세요");
넵 반영하겠습니다.

2023-06-30 00:57 UTC, hafnium1923 commented on src/api/store/fetchStoreList.tsx
> +    accessToken === null ? nonUserFetchOptions : userFetchOptions
accessToken이 없다는 것을 명시하려고 했던 것 같습니다! 말씀해주신 방법으로 변경하도록 하겠습니다.

2023-06-30 01:19 UTC, hafnium1923 commented on src/hooks/useBookmark.ts
> +      alert("오류가 발생했습니다. 잠시 후 다시 시도해주세요.");
앗 확인했습니다!

2023-06-30 01:47 UTC, hafnium1923 commented on src/hooks/useBookmark.ts
> +    bookmark ? deleteBookmark.mutate() : postBookmark.mutate();
한번 적용해봤습니다만 debounce를 처음 사용해봐서 좋은 코드인진 잘 모르겠습니다!

2023-06-30 01:48 UTC, hafnium1923 commented on src/components/pages/StoreDetailPage/StoreDetailTitle/StoreDetailTitle.tsx
> +  const { bookmark, handleBookmark } = useBookmark(id, saved);
넵 변경하겠습니다.

2023-06-30 02:03 UTC, hafnium1923 commented on src/components/common/StoreListItem/StoreListItem.tsx
> +      <S.ListItemBookmark onClick={handleBookmark}>
스타일링이 쉽기 때문입니다. button을 사용하게 된다면 기본 css가 있어서 reset 시키는 과정이 굉장히 귀찮다고 생각했기 때문에 div으로 했었습니다. button으로 바꿔보겠습니다.🥲

2023-06-30 07:15 UTC, nan-noo commented on README.md
요건 다른 코드에 영향 미치는 게 아니라서 크게 상관은 없지만..! 리드미 같은 거 수정은 이번 PR과 주제가 다르니까 분리하는 게 좋다고 생각해요! 지금 없애라는 이야긴 아니에요!

2023-06-30 07:17 UTC, nan-noo commented on src/components/common/StoreListItem/StoreListItem.tsx
> +      <S.ListItemBookmark onClick={handleBookmark}>
적절한 요소를 사용하는 게 접근성에도 아마 좋을거에요!

2023-06-30 07:53 UTC, nan-noo approved these changes
그냥 지금 든 생각인데, 로그인 안 했을 때는 하트를 아예 안 보여주는 게 맞지 않을까요??

2023-06-30 07:53 UTC, nan-noo commented on src/components/common/StoreListItem/StoreListItem.tsx
> +import { useBookmark } from "hooks/useMarked";
파일명은 useMarked인데 훅 이름은 useBookmark에요!

2023-06-30 07:53 UTC, nan-noo commented on src/hooks/useMarked.ts
> +  };
제가 생각한 방식은 그냥 가장 단순하게 적용하는 거였어요!

```ts
  const debounceIdRef = useRef<null | ReturnType<typeof 
  setTimeout>>(null);

  ...

  const handleMarked = (event: MouseEvent<HTMLButtonElement>) => {
    event.stopPropagation();

    if (debounceIdRef.current) clearTimeout(debounceIdRef.current);
    debounceIdRef.current = setTimeout(() => {
      marked ? deleteBookmark.mutate() : postBookmark.mutate();
    }, 1000);

    setMarked((prevMarked) => !prevMarked);
  };
```

클릭이 막히는 것처럼 보이면 안되니까 state는 클릭할 때마다 바뀌지만 api 요청은 지연되도록! (시간은 임의 설정한거에요)
ref로 한 이유는 ref 값은 바뀌어도 렌더링이 안되니까.. 입니다!

타임이랑 콜백 함수를 인자로 받는 debounce 함수를 만들어서 사용해도 돼요

2023-07-01 14:37 UTC, hafnium1923 commented on README.md
넵! 다음부터는 분리해서 작성하도록 하겠습니다!

2023-07-01 14:38 UTC, hafnium1923 commented on src/components/common/StoreListItem/StoreListItem.tsx
> +      <S.ListItemBookmark onClick={handleBookmark}>
넵! 조금 더 신경써서 해보겠습니다ㅎㅎ

2023-07-01 14:43 UTC, hafnium1923 commented on src/components/common/StoreListItem/StoreListItem.tsx
> +import { useBookmark } from "hooks/useMarked";
헉 깜빡했나봅니다! 바로 수정했습니다.

2023-07-01 15:13 UTC, hafnium1923 commented on src/hooks/useMarked.ts
> +  };
오 ref에 함수를 할당할 수 있네요! 처음 봤어요!! 알려주신 방법으로 바꿔두겠습니다

2023-07-01 15:15 UTC, hafnium1923 commented
그냥 지금 든 생각인데, 로그인 안 했을 때는 하트를 아예 안 보여주는 게 맞지 않을까요??
- 이건 어떤 의도였냐면 로그인 안한 사람들이 호기심에 눌러봤을 때 로그인/회원가입을 해서 찜 기능을 사용할 수 있게 하려는 의도입니다! 로그인 안했을 때 기능이 있다는 것을 알려준다면 좀 더 적극적으로 이용할 수 있지 않을까 해서요

2023-07-03 03:49 UTC, merged